site_name: My Notes
site_url: https://zhyun828.github.io/

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: 深色模式
    - scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: 浅色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - toc:
      permalink: true

nav:
  - 主页: index.md

  - 笔记:
      - Arduino:
          - 基础: notes/Arduino/basics.md
          - 项目:
              - 项目说明: notes/Arduino/projet/projet.md
              - 项目前期: notes/Arduino/projet/pre.md
              - 代码说明: notes/Arduino/projet/code.md
              - 项目反思: notes/Arduino/projet/thoughts.md

      - C++:
          - 基础语法: notes/Cpp/basics.md
          - 面向对象: notes/Cpp/opp.md

      - FPGA / VHDL:
          - 基础知识: notes/FPGA/basics.md
